#!/usr/bin/python3
import beets

with beets.connect() as conn:

    for (item,title,album) in conn.execute("SELECT items.id,items.title,items.album_id FROM items LEFT OUTER JOIN albums ON items.album_id = albums.id WHERE albums.id IS NULL"):
        print ("Missing album: id "+str(item)+" "+title)    

    for (album_guid,a_artist,a_album,b_artist,b_album) in conn.execute("SELECT a.mb_albumid, a.albumartist, a.album, b.albumartist, b.album FROM albums AS a, albums AS b WHERE a.mb_albumid = b.mb_albumid AND b.id > a.id"):
        print ("Duplicate album: " + album_guid )
        print ("  " + a_artist + " - " + a_album)
        print ("  " + b_artist + " - " + b_album)

    for (a_guid,b_guid,artist,album) in conn.execute("SELECT a.mb_albumid, b.mb_albumid, a.albumartist, a.album FROM albums AS a, albums AS b WHERE a.albumartist = b.albumartist AND a.album = b.album AND b.mb_albumid > a.mb_albumid"):
        print ("Similar albums: " + artist + " - " + album )
        print ("  " + a_guid)
        print ("  " + b_guid)
